### PR TITLE
Update restaurants.html

### PR DESCRIPTION
**Pull request by kirakosyan**
bug fix

### CODE REVIEW

**Comment by gnomeontherun** [comment]
Thanks, I'll get this synced and rebase so it matches what is in the book!

**Comment by gnomeontherun** [comment]
Fixed in rebased master, thanks!

**Comment by kirakosyan** [comment]
Hi, My pleasure.
And thank you for the book, I am reading it on Safari :) 
Really good one.

**Comment by gnomeontherun** [comment]
Thanks! I'm glad you enjoy it!

**Pull request closed without merging**
